version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: weather-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Kdk@2003
      MYSQL_DATABASE: weatherdb
      MYSQL_USER: weatheruser
      MYSQL_PASSWORD: weatherpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./weather-backend
      dockerfile: Dockerfile
    container_name: weather-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/weatherdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: weatheruser
      SPRING_DATASOURCE_PASSWORD: weatherpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: mySecretKey123456789012345678901234567890
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./weather-frontend
      dockerfile: Dockerfile
    container_name: weather-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
